language: viml

sudo: false

os:
    - linux

install:
    # Install Neovim via Gist
    # https://gist.github.com/lambdalisue/0f461f6a91743895394e63a9a1c65232
    - curl -sL https://gist.githubusercontent.com/lambdalisue/0f461f6a91743895394e63a9a1c65232/raw/install_nvim_for_ci.sh | bash
    - make install

before_script:
    - git clone https://github.com/thinca/vim-themis

script:
    - THEMIS_VIM="$HOME/neovim/bin/nvim" vim-themis/bin/themis --reporter spec
