dist: xenial

language: viml

install:
  - eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"
  - make install

script:
  - make --keep-going test
